# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a99578a275069d1c164d031a569bee130f7018e6580df2f44dd631f888e53de305e3b8bf64db46e7e9856c66e430db997da62fc4de24725a3b5683c6c2777ae3

test:
  secret_key_base: 33456083c47415fb9cf1e894c6de6653f1719a28baef98d69042ffd76cda25c301bb89799181d89b0d6c2f724ffc164ab71abab52d880f702399f4dc4bf86fc9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
